version: 0.1.{build}-prealpha

branches:
  only:
    - master

init:
  - git config --global core.autocrlf input

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}" #Remember to add [assembly: AssemblyInformationalVersion("")] in assemblyinfo.cs

configuration: Debug

build:
  publish_nuget: true
  publish_nuget_symbols: true

test: off
  
deploy:
  - provider: NuGet
    api_key:
      secure: 5BZUajFAXPWc0ccaBvpYU08ye57+IeA6ilWKW2ticeBZu16/TtASAVTt1RkNkOCl

