branches:
  only:
    - master

version: 0.1.0.{build}-prealpha

init:
  - git config --global core.autocrlf input

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

before_deploy:
  - nuget pack HelloWorldLib.csproj -Version "%APPVEYOR_BUILD_VERSION%"

deploy:
  - provider: NuGet
    api_key:
      secure: 5BZUajFAXPWc0ccaBvpYU08ye57+IeA6ilWKW2ticeBZu16/TtASAVTt1RkNkOCl