version: 1.0.{build}
branches:
  only:
    - master

init:
  - git config --global core.autocrlf input

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "0.1.{build}-prealpha"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

deploy:
  - provider: NuGet
    api_key:
      secure: 5BZUajFAXPWc0ccaBvpYU08ye57+IeA6ilWKW2ticeBZu16/TtASAVTt1RkNkOCl